version: '2'

services:
  github-releases-notifier:
    restart: always
    image: justwatch/github-releases-notifier
    environment:
      - GITHUB_TOKEN=XXX
      - SLACK_HOOK=https://hooks.slack.com/services/T02MASDF7/B6WERHYRZ/XXX
    command:
      - '-r=github.com/golang/go'
      - '-r=github.com/justwatchcom/elasticsearch_exporter'
      - '-r=github.com/justwatchcom/gopass'
      - '-r=github.com/justwatchcom/sql_exporter'
      - '-r=github.com/kubernetes/minikube'
      - '-r=github.com/prometheus/prometheus'
      - '-r=github.com/shurcooL/githubql'
